// Code generated by go-swagger; DO NOT EDIT.

package edge_configs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEdgeConfigCreateParams creates a new EdgeConfigCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEdgeConfigCreateParams() *EdgeConfigCreateParams {
	return &EdgeConfigCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEdgeConfigCreateParamsWithTimeout creates a new EdgeConfigCreateParams object
// with the ability to set a timeout on a request.
func NewEdgeConfigCreateParamsWithTimeout(timeout time.Duration) *EdgeConfigCreateParams {
	return &EdgeConfigCreateParams{
		timeout: timeout,
	}
}

// NewEdgeConfigCreateParamsWithContext creates a new EdgeConfigCreateParams object
// with the ability to set a context for a request.
func NewEdgeConfigCreateParamsWithContext(ctx context.Context) *EdgeConfigCreateParams {
	return &EdgeConfigCreateParams{
		Context: ctx,
	}
}

// NewEdgeConfigCreateParamsWithHTTPClient creates a new EdgeConfigCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewEdgeConfigCreateParamsWithHTTPClient(client *http.Client) *EdgeConfigCreateParams {
	return &EdgeConfigCreateParams{
		HTTPClient: client,
	}
}

/*
EdgeConfigCreateParams contains all the parameters to send to the API endpoint

	for the edge config create operation.

	Typically these are written to a http.Request.
*/
type EdgeConfigCreateParams struct {

	/* File.

	   File
	*/
	File runtime.NamedReadCloser

	// BaseDir.
	BaseDir *string

	// Category.
	Category *string

	// EdgeGroupIDs.
	EdgeGroupIDs []int64

	// Name.
	Name *string

	// Type.
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edge config create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeConfigCreateParams) WithDefaults() *EdgeConfigCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edge config create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeConfigCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edge config create params
func (o *EdgeConfigCreateParams) WithTimeout(timeout time.Duration) *EdgeConfigCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edge config create params
func (o *EdgeConfigCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edge config create params
func (o *EdgeConfigCreateParams) WithContext(ctx context.Context) *EdgeConfigCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edge config create params
func (o *EdgeConfigCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edge config create params
func (o *EdgeConfigCreateParams) WithHTTPClient(client *http.Client) *EdgeConfigCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edge config create params
func (o *EdgeConfigCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the edge config create params
func (o *EdgeConfigCreateParams) WithFile(file runtime.NamedReadCloser) *EdgeConfigCreateParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the edge config create params
func (o *EdgeConfigCreateParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WithBaseDir adds the baseDir to the edge config create params
func (o *EdgeConfigCreateParams) WithBaseDir(baseDir *string) *EdgeConfigCreateParams {
	o.SetBaseDir(baseDir)
	return o
}

// SetBaseDir adds the baseDir to the edge config create params
func (o *EdgeConfigCreateParams) SetBaseDir(baseDir *string) {
	o.BaseDir = baseDir
}

// WithCategory adds the category to the edge config create params
func (o *EdgeConfigCreateParams) WithCategory(category *string) *EdgeConfigCreateParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the edge config create params
func (o *EdgeConfigCreateParams) SetCategory(category *string) {
	o.Category = category
}

// WithEdgeGroupIDs adds the edgeGroupIDs to the edge config create params
func (o *EdgeConfigCreateParams) WithEdgeGroupIDs(edgeGroupIDs []int64) *EdgeConfigCreateParams {
	o.SetEdgeGroupIDs(edgeGroupIDs)
	return o
}

// SetEdgeGroupIDs adds the edgeGroupIDs to the edge config create params
func (o *EdgeConfigCreateParams) SetEdgeGroupIDs(edgeGroupIDs []int64) {
	o.EdgeGroupIDs = edgeGroupIDs
}

// WithName adds the name to the edge config create params
func (o *EdgeConfigCreateParams) WithName(name *string) *EdgeConfigCreateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the edge config create params
func (o *EdgeConfigCreateParams) SetName(name *string) {
	o.Name = name
}

// WithType adds the typeVar to the edge config create params
func (o *EdgeConfigCreateParams) WithType(typeVar *string) *EdgeConfigCreateParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the edge config create params
func (o *EdgeConfigCreateParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *EdgeConfigCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param File
	if err := r.SetFileParam("File", o.File); err != nil {
		return err
	}

	if o.BaseDir != nil {

		// form param baseDir
		var frBaseDir string
		if o.BaseDir != nil {
			frBaseDir = *o.BaseDir
		}
		fBaseDir := frBaseDir
		if fBaseDir != "" {
			if err := r.SetFormParam("baseDir", fBaseDir); err != nil {
				return err
			}
		}
	}

	if o.Category != nil {

		// form param category
		var frCategory string
		if o.Category != nil {
			frCategory = *o.Category
		}
		fCategory := frCategory
		if fCategory != "" {
			if err := r.SetFormParam("category", fCategory); err != nil {
				return err
			}
		}
	}

	if o.EdgeGroupIDs != nil {

		// binding items for edgeGroupIDs
		joinedEdgeGroupIDs := o.bindParamEdgeGroupIDs(reg)

		// form array param edgeGroupIDs
		if err := r.SetFormParam("edgeGroupIDs", joinedEdgeGroupIDs...); err != nil {
			return err
		}
	}

	if o.Name != nil {

		// form param name
		var frName string
		if o.Name != nil {
			frName = *o.Name
		}
		fName := frName
		if fName != "" {
			if err := r.SetFormParam("name", fName); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// form param type
		var frType string
		if o.Type != nil {
			frType = *o.Type
		}
		fType := frType
		if fType != "" {
			if err := r.SetFormParam("type", fType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamEdgeConfigCreate binds the parameter edgeGroupIDs
func (o *EdgeConfigCreateParams) bindParamEdgeGroupIDs(formats strfmt.Registry) []string {
	edgeGroupIDsIR := o.EdgeGroupIDs

	var edgeGroupIDsIC []string
	for _, edgeGroupIDsIIR := range edgeGroupIDsIR { // explode []int64

		edgeGroupIDsIIV := swag.FormatInt64(edgeGroupIDsIIR) // int64 as string
		edgeGroupIDsIC = append(edgeGroupIDsIC, edgeGroupIDsIIV)
	}

	// items.CollectionFormat: "csv"
	edgeGroupIDsIS := swag.JoinByFormat(edgeGroupIDsIC, "csv")

	return edgeGroupIDsIS
}
