// Code generated by go-swagger; DO NOT EDIT.

package edge_configs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// EdgeConfigInspectReader is a Reader for the EdgeConfigInspect structure.
type EdgeConfigInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeConfigInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeConfigInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeConfigInspectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeConfigInspectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeConfigInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /edge_configurations/{id}] EdgeConfigInspect", response, response.Code())
	}
}

// NewEdgeConfigInspectOK creates a EdgeConfigInspectOK with default headers values
func NewEdgeConfigInspectOK() *EdgeConfigInspectOK {
	return &EdgeConfigInspectOK{}
}

/*
EdgeConfigInspectOK describes a response with status code 200, with default header values.

Success
*/
type EdgeConfigInspectOK struct {
	Payload *models.PortainereeEdgeConfig
}

// IsSuccess returns true when this edge config inspect o k response has a 2xx status code
func (o *EdgeConfigInspectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge config inspect o k response has a 3xx status code
func (o *EdgeConfigInspectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge config inspect o k response has a 4xx status code
func (o *EdgeConfigInspectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge config inspect o k response has a 5xx status code
func (o *EdgeConfigInspectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge config inspect o k response a status code equal to that given
func (o *EdgeConfigInspectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge config inspect o k response
func (o *EdgeConfigInspectOK) Code() int {
	return 200
}

func (o *EdgeConfigInspectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectOK %s", 200, payload)
}

func (o *EdgeConfigInspectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectOK %s", 200, payload)
}

func (o *EdgeConfigInspectOK) GetPayload() *models.PortainereeEdgeConfig {
	return o.Payload
}

func (o *EdgeConfigInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortainereeEdgeConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewEdgeConfigInspectBadRequest creates a EdgeConfigInspectBadRequest with default headers values
func NewEdgeConfigInspectBadRequest() *EdgeConfigInspectBadRequest {
	return &EdgeConfigInspectBadRequest{}
}

/*
EdgeConfigInspectBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type EdgeConfigInspectBadRequest struct {
}

// IsSuccess returns true when this edge config inspect bad request response has a 2xx status code
func (o *EdgeConfigInspectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge config inspect bad request response has a 3xx status code
func (o *EdgeConfigInspectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge config inspect bad request response has a 4xx status code
func (o *EdgeConfigInspectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge config inspect bad request response has a 5xx status code
func (o *EdgeConfigInspectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge config inspect bad request response a status code equal to that given
func (o *EdgeConfigInspectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge config inspect bad request response
func (o *EdgeConfigInspectBadRequest) Code() int {
	return 400
}

func (o *EdgeConfigInspectBadRequest) Error() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectBadRequest", 400)
}

func (o *EdgeConfigInspectBadRequest) String() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectBadRequest", 400)
}

func (o *EdgeConfigInspectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeConfigInspectNotFound creates a EdgeConfigInspectNotFound with default headers values
func NewEdgeConfigInspectNotFound() *EdgeConfigInspectNotFound {
	return &EdgeConfigInspectNotFound{}
}

/*
EdgeConfigInspectNotFound describes a response with status code 404, with default header values.

Edge configuration not found
*/
type EdgeConfigInspectNotFound struct {
}

// IsSuccess returns true when this edge config inspect not found response has a 2xx status code
func (o *EdgeConfigInspectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge config inspect not found response has a 3xx status code
func (o *EdgeConfigInspectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge config inspect not found response has a 4xx status code
func (o *EdgeConfigInspectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge config inspect not found response has a 5xx status code
func (o *EdgeConfigInspectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge config inspect not found response a status code equal to that given
func (o *EdgeConfigInspectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge config inspect not found response
func (o *EdgeConfigInspectNotFound) Code() int {
	return 404
}

func (o *EdgeConfigInspectNotFound) Error() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectNotFound", 404)
}

func (o *EdgeConfigInspectNotFound) String() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectNotFound", 404)
}

func (o *EdgeConfigInspectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeConfigInspectInternalServerError creates a EdgeConfigInspectInternalServerError with default headers values
func NewEdgeConfigInspectInternalServerError() *EdgeConfigInspectInternalServerError {
	return &EdgeConfigInspectInternalServerError{}
}

/*
EdgeConfigInspectInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type EdgeConfigInspectInternalServerError struct {
}

// IsSuccess returns true when this edge config inspect internal server error response has a 2xx status code
func (o *EdgeConfigInspectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge config inspect internal server error response has a 3xx status code
func (o *EdgeConfigInspectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge config inspect internal server error response has a 4xx status code
func (o *EdgeConfigInspectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge config inspect internal server error response has a 5xx status code
func (o *EdgeConfigInspectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge config inspect internal server error response a status code equal to that given
func (o *EdgeConfigInspectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge config inspect internal server error response
func (o *EdgeConfigInspectInternalServerError) Code() int {
	return 500
}

func (o *EdgeConfigInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectInternalServerError", 500)
}

func (o *EdgeConfigInspectInternalServerError) String() string {
	return fmt.Sprintf("[GET /edge_configurations/{id}][%d] edgeConfigInspectInternalServerError", 500)
}

func (o *EdgeConfigInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
