// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSettingsAdditionalFunctionalityInspectParams creates a new SettingsAdditionalFunctionalityInspectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSettingsAdditionalFunctionalityInspectParams() *SettingsAdditionalFunctionalityInspectParams {
	return &SettingsAdditionalFunctionalityInspectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSettingsAdditionalFunctionalityInspectParamsWithTimeout creates a new SettingsAdditionalFunctionalityInspectParams object
// with the ability to set a timeout on a request.
func NewSettingsAdditionalFunctionalityInspectParamsWithTimeout(timeout time.Duration) *SettingsAdditionalFunctionalityInspectParams {
	return &SettingsAdditionalFunctionalityInspectParams{
		timeout: timeout,
	}
}

// NewSettingsAdditionalFunctionalityInspectParamsWithContext creates a new SettingsAdditionalFunctionalityInspectParams object
// with the ability to set a context for a request.
func NewSettingsAdditionalFunctionalityInspectParamsWithContext(ctx context.Context) *SettingsAdditionalFunctionalityInspectParams {
	return &SettingsAdditionalFunctionalityInspectParams{
		Context: ctx,
	}
}

// NewSettingsAdditionalFunctionalityInspectParamsWithHTTPClient creates a new SettingsAdditionalFunctionalityInspectParams object
// with the ability to set a custom HTTPClient for a request.
func NewSettingsAdditionalFunctionalityInspectParamsWithHTTPClient(client *http.Client) *SettingsAdditionalFunctionalityInspectParams {
	return &SettingsAdditionalFunctionalityInspectParams{
		HTTPClient: client,
	}
}

/*
SettingsAdditionalFunctionalityInspectParams contains all the parameters to send to the API endpoint

	for the settings additional functionality inspect operation.

	Typically these are written to a http.Request.
*/
type SettingsAdditionalFunctionalityInspectParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the settings additional functionality inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SettingsAdditionalFunctionalityInspectParams) WithDefaults() *SettingsAdditionalFunctionalityInspectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the settings additional functionality inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SettingsAdditionalFunctionalityInspectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) WithTimeout(timeout time.Duration) *SettingsAdditionalFunctionalityInspectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) WithContext(ctx context.Context) *SettingsAdditionalFunctionalityInspectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) WithHTTPClient(client *http.Client) *SettingsAdditionalFunctionalityInspectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the settings additional functionality inspect params
func (o *SettingsAdditionalFunctionalityInspectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SettingsAdditionalFunctionalityInspectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
