// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AutoupdatesListResponse autoupdates list response
//
// swagger:model autoupdates.listResponse
type AutoupdatesListResponse struct {

	// auto updates
	AutoUpdates []*AutoupdatesAutoUpdateResponseItem `json:"autoUpdates"`
}

// Validate validates this autoupdates list response
func (m *AutoupdatesListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutoUpdates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AutoupdatesListResponse) validateAutoUpdates(formats strfmt.Registry) error {
	if swag.IsZero(m.AutoUpdates) { // not required
		return nil
	}

	for i := 0; i < len(m.AutoUpdates); i++ {
		if swag.IsZero(m.AutoUpdates[i]) { // not required
			continue
		}

		if m.AutoUpdates[i] != nil {
			if err := m.AutoUpdates[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("autoUpdates" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("autoUpdates" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this autoupdates list response based on the context it is used
func (m *AutoupdatesListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAutoUpdates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AutoupdatesListResponse) contextValidateAutoUpdates(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AutoUpdates); i++ {

		if m.AutoUpdates[i] != nil {

			if swag.IsZero(m.AutoUpdates[i]) { // not required
				return nil
			}

			if err := m.AutoUpdates[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("autoUpdates" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("autoUpdates" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AutoupdatesListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AutoupdatesListResponse) UnmarshalBinary(b []byte) error {
	var res AutoupdatesListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
