// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPortainerPortainerPkgLibhelmReleaseHook github com portainer portainer pkg libhelm release hook
//
// swagger:model github_com_portainer_portainer_pkg_libhelm_release.Hook
type GithubComPortainerPortainerPkgLibhelmReleaseHook struct {

	// DeletePolicies are the policies that indicate when to delete the hook
	DeletePolicies []string `json:"delete_policies"`

	// Events are the events that this hook fires on.
	Events []string `json:"events"`

	// Kind is the Kubernetes kind.
	Kind string `json:"kind,omitempty"`

	// LastRun indicates the date/time this was last run.
	LastRun struct {
		GithubComPortainerPortainerPkgLibhelmReleaseHookExecution
	} `json:"last_run,omitempty"`

	// Manifest is the manifest contents.
	Manifest string `json:"manifest,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Path is the chart-relative path to the template.
	Path string `json:"path,omitempty"`

	// Weight indicates the sort order for execution among similar Hook type
	Weight int64 `json:"weight,omitempty"`
}

// Validate validates this github com portainer portainer pkg libhelm release hook
func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastRun(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) validateLastRun(formats strfmt.Registry) error {
	if swag.IsZero(m.LastRun) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this github com portainer portainer pkg libhelm release hook based on the context it is used
func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastRun(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) contextValidateLastRun(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPortainerPortainerPkgLibhelmReleaseHook) UnmarshalBinary(b []byte) error {
	var res GithubComPortainerPortainerPkgLibhelmReleaseHook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
