// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HelmGitHelmDryRunPayload helm git helm dry run payload
//
// swagger:model helm.gitHelmDryRunPayload
type HelmGitHelmDryRunPayload struct {

	// helm chart path
	HelmChartPath string `json:"helmChartPath,omitempty"`

	// helm values files
	HelmValuesFiles []string `json:"helmValuesFiles"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// repository authentication
	RepositoryAuthentication bool `json:"repositoryAuthentication,omitempty"`

	// repository authorization type
	RepositoryAuthorizationType GittypesGitCredentialAuthType `json:"repositoryAuthorizationType,omitempty"`

	// repository git credential ID
	RepositoryGitCredentialID int64 `json:"repositoryGitCredentialID,omitempty"`

	// repository password
	RepositoryPassword string `json:"repositoryPassword,omitempty"`

	// repository reference name
	RepositoryReferenceName string `json:"repositoryReferenceName,omitempty"`

	// repository URL
	RepositoryURL string `json:"repositoryURL,omitempty"`

	// repository username
	RepositoryUsername string `json:"repositoryUsername,omitempty"`

	// tls skip verify
	TLSSkipVerify bool `json:"tlsSkipVerify,omitempty"`
}

// Validate validates this helm git helm dry run payload
func (m *HelmGitHelmDryRunPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRepositoryAuthorizationType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HelmGitHelmDryRunPayload) validateRepositoryAuthorizationType(formats strfmt.Registry) error {
	if swag.IsZero(m.RepositoryAuthorizationType) { // not required
		return nil
	}

	if err := m.RepositoryAuthorizationType.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("repositoryAuthorizationType")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("repositoryAuthorizationType")
		}

		return err
	}

	return nil
}

// ContextValidate validate this helm git helm dry run payload based on the context it is used
func (m *HelmGitHelmDryRunPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRepositoryAuthorizationType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HelmGitHelmDryRunPayload) contextValidateRepositoryAuthorizationType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.RepositoryAuthorizationType) { // not required
		return nil
	}

	if err := m.RepositoryAuthorizationType.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("repositoryAuthorizationType")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("repositoryAuthorizationType")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HelmGitHelmDryRunPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HelmGitHelmDryRunPayload) UnmarshalBinary(b []byte) error {
	var res HelmGitHelmDryRunPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
