// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsK8sServicePort models k8s service port
//
// swagger:model models.K8sServicePort
type ModelsK8sServicePort struct {

	// name
	Name string `json:"Name,omitempty"`

	// node port
	NodePort int64 `json:"NodePort,omitempty"`

	// port
	Port int64 `json:"Port,omitempty"`

	// protocol
	Protocol string `json:"Protocol,omitempty"`

	// target port
	TargetPort string `json:"TargetPort,omitempty"`
}

// Validate validates this models k8s service port
func (m *ModelsK8sServicePort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models k8s service port based on context it is used
func (m *ModelsK8sServicePort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsK8sServicePort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsK8sServicePort) UnmarshalBinary(b []byte) error {
	var res ModelsK8sServicePort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
