// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PodsecurityFSType podsecurity f s type
//
// swagger:model podsecurity.FSType
type PodsecurityFSType string

func NewPodsecurityFSType(value PodsecurityFSType) *PodsecurityFSType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PodsecurityFSType.
func (m PodsecurityFSType) Pointer() *PodsecurityFSType {
	return &m
}

const (

	// PodsecurityFSTypeAzureFile captures enum value "azureFile"
	PodsecurityFSTypeAzureFile PodsecurityFSType = "azureFile"

	// PodsecurityFSTypeFlocker captures enum value "flocker"
	PodsecurityFSTypeFlocker PodsecurityFSType = "flocker"

	// PodsecurityFSTypeFlexVolume captures enum value "flexVolume"
	PodsecurityFSTypeFlexVolume PodsecurityFSType = "flexVolume"

	// PodsecurityFSTypeHostPath captures enum value "hostPath"
	PodsecurityFSTypeHostPath PodsecurityFSType = "hostPath"

	// PodsecurityFSTypeEmptyDir captures enum value "emptyDir"
	PodsecurityFSTypeEmptyDir PodsecurityFSType = "emptyDir"

	// PodsecurityFSTypeGcePersistentDisk captures enum value "gcePersistentDisk"
	PodsecurityFSTypeGcePersistentDisk PodsecurityFSType = "gcePersistentDisk"

	// PodsecurityFSTypeAwsElasticBlockStore captures enum value "awsElasticBlockStore"
	PodsecurityFSTypeAwsElasticBlockStore PodsecurityFSType = "awsElasticBlockStore"

	// PodsecurityFSTypeGitRepo captures enum value "gitRepo"
	PodsecurityFSTypeGitRepo PodsecurityFSType = "gitRepo"

	// PodsecurityFSTypeSecret captures enum value "secret"
	PodsecurityFSTypeSecret PodsecurityFSType = "secret"

	// PodsecurityFSTypeNfs captures enum value "nfs"
	PodsecurityFSTypeNfs PodsecurityFSType = "nfs"

	// PodsecurityFSTypeIscsi captures enum value "iscsi"
	PodsecurityFSTypeIscsi PodsecurityFSType = "iscsi"

	// PodsecurityFSTypeGlusterfs captures enum value "glusterfs"
	PodsecurityFSTypeGlusterfs PodsecurityFSType = "glusterfs"

	// PodsecurityFSTypePersistentVolumeClaim captures enum value "persistentVolumeClaim"
	PodsecurityFSTypePersistentVolumeClaim PodsecurityFSType = "persistentVolumeClaim"

	// PodsecurityFSTypeRbd captures enum value "rbd"
	PodsecurityFSTypeRbd PodsecurityFSType = "rbd"

	// PodsecurityFSTypeCinder captures enum value "cinder"
	PodsecurityFSTypeCinder PodsecurityFSType = "cinder"

	// PodsecurityFSTypeCephFS captures enum value "cephFS"
	PodsecurityFSTypeCephFS PodsecurityFSType = "cephFS"

	// PodsecurityFSTypeDownwardAPI captures enum value "downwardAPI"
	PodsecurityFSTypeDownwardAPI PodsecurityFSType = "downwardAPI"

	// PodsecurityFSTypeFc captures enum value "fc"
	PodsecurityFSTypeFc PodsecurityFSType = "fc"

	// PodsecurityFSTypeConfigMap captures enum value "configMap"
	PodsecurityFSTypeConfigMap PodsecurityFSType = "configMap"

	// PodsecurityFSTypeVsphereVolume captures enum value "vsphereVolume"
	PodsecurityFSTypeVsphereVolume PodsecurityFSType = "vsphereVolume"

	// PodsecurityFSTypeQuobyte captures enum value "quobyte"
	PodsecurityFSTypeQuobyte PodsecurityFSType = "quobyte"

	// PodsecurityFSTypeAzureDisk captures enum value "azureDisk"
	PodsecurityFSTypeAzureDisk PodsecurityFSType = "azureDisk"

	// PodsecurityFSTypePhotonPersistentDisk captures enum value "photonPersistentDisk"
	PodsecurityFSTypePhotonPersistentDisk PodsecurityFSType = "photonPersistentDisk"

	// PodsecurityFSTypeStorageos captures enum value "storageos"
	PodsecurityFSTypeStorageos PodsecurityFSType = "storageos"

	// PodsecurityFSTypeProjected captures enum value "projected"
	PodsecurityFSTypeProjected PodsecurityFSType = "projected"

	// PodsecurityFSTypePortworxVolume captures enum value "portworxVolume"
	PodsecurityFSTypePortworxVolume PodsecurityFSType = "portworxVolume"

	// PodsecurityFSTypeScaleIO captures enum value "scaleIO"
	PodsecurityFSTypeScaleIO PodsecurityFSType = "scaleIO"

	// PodsecurityFSTypeCsi captures enum value "csi"
	PodsecurityFSTypeCsi PodsecurityFSType = "csi"

	// PodsecurityFSTypeEphemeral captures enum value "ephemeral"
	PodsecurityFSTypeEphemeral PodsecurityFSType = "ephemeral"

	// PodsecurityFSTypeAsterisk captures enum value "*"
	PodsecurityFSTypeAsterisk PodsecurityFSType = "*"
)

// for schema
var podsecurityFSTypeEnum []any

func init() {
	var res []PodsecurityFSType
	if err := json.Unmarshal([]byte(`["azureFile","flocker","flexVolume","hostPath","emptyDir","gcePersistentDisk","awsElasticBlockStore","gitRepo","secret","nfs","iscsi","glusterfs","persistentVolumeClaim","rbd","cinder","cephFS","downwardAPI","fc","configMap","vsphereVolume","quobyte","azureDisk","photonPersistentDisk","storageos","projected","portworxVolume","scaleIO","csi","ephemeral","*"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		podsecurityFSTypeEnum = append(podsecurityFSTypeEnum, v)
	}
}

func (m PodsecurityFSType) validatePodsecurityFSTypeEnum(path, location string, value PodsecurityFSType) error {
	if err := validate.EnumCase(path, location, value, podsecurityFSTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this podsecurity f s type
func (m PodsecurityFSType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePodsecurityFSTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this podsecurity f s type based on context it is used
func (m PodsecurityFSType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
