// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PortainerTeamResourceAccess portainer team resource access
//
// swagger:model portainer.TeamResourceAccess
type PortainerTeamResourceAccess struct {

	// access level
	AccessLevel PortainerResourceAccessLevel `json:"AccessLevel,omitempty"`

	// team Id
	TeamID int64 `json:"TeamId,omitempty"`
}

// Validate validates this portainer team resource access
func (m *PortainerTeamResourceAccess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessLevel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortainerTeamResourceAccess) validateAccessLevel(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessLevel) { // not required
		return nil
	}

	if err := m.AccessLevel.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("AccessLevel")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("AccessLevel")
		}

		return err
	}

	return nil
}

// ContextValidate validate this portainer team resource access based on the context it is used
func (m *PortainerTeamResourceAccess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessLevel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortainerTeamResourceAccess) contextValidateAccessLevel(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.AccessLevel) { // not required
		return nil
	}

	if err := m.AccessLevel.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("AccessLevel")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("AccessLevel")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PortainerTeamResourceAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortainerTeamResourceAccess) UnmarshalBinary(b []byte) error {
	var res PortainerTeamResourceAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
