// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PortainereeAutoUpdateStatus portaineree auto update status
//
// swagger:model portaineree.AutoUpdateStatus
type PortainereeAutoUpdateStatus string

func NewPortainereeAutoUpdateStatus(value PortainereeAutoUpdateStatus) *PortainereeAutoUpdateStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PortainereeAutoUpdateStatus.
func (m PortainereeAutoUpdateStatus) Pointer() *PortainereeAutoUpdateStatus {
	return &m
}

const (

	// PortainereeAutoUpdateStatusInProgress captures enum value "inProgress"
	PortainereeAutoUpdateStatusInProgress PortainereeAutoUpdateStatus = "inProgress"

	// PortainereeAutoUpdateStatusCompleted captures enum value "completed"
	PortainereeAutoUpdateStatusCompleted PortainereeAutoUpdateStatus = "completed"

	// PortainereeAutoUpdateStatusFailed captures enum value "failed"
	PortainereeAutoUpdateStatusFailed PortainereeAutoUpdateStatus = "failed"
)

// for schema
var portainereeAutoUpdateStatusEnum []any

func init() {
	var res []PortainereeAutoUpdateStatus
	if err := json.Unmarshal([]byte(`["inProgress","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		portainereeAutoUpdateStatusEnum = append(portainereeAutoUpdateStatusEnum, v)
	}
}

func (m PortainereeAutoUpdateStatus) validatePortainereeAutoUpdateStatusEnum(path, location string, value PortainereeAutoUpdateStatus) error {
	if err := validate.EnumCase(path, location, value, portainereeAutoUpdateStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this portaineree auto update status
func (m PortainereeAutoUpdateStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePortainereeAutoUpdateStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this portaineree auto update status based on context it is used
func (m PortainereeAutoUpdateStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
