// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PortainerPerDevConfigsFilterType portainer per dev configs filter type
//
// swagger:model portainer.PerDevConfigsFilterType
type PortainerPerDevConfigsFilterType string

func NewPortainerPerDevConfigsFilterType(value PortainerPerDevConfigsFilterType) *PortainerPerDevConfigsFilterType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PortainerPerDevConfigsFilterType.
func (m PortainerPerDevConfigsFilterType) Pointer() *PortainerPerDevConfigsFilterType {
	return &m
}

const (

	// PortainerPerDevConfigsFilterTypeFile captures enum value "file"
	PortainerPerDevConfigsFilterTypeFile PortainerPerDevConfigsFilterType = "file"

	// PortainerPerDevConfigsFilterTypeDir captures enum value "dir"
	PortainerPerDevConfigsFilterTypeDir PortainerPerDevConfigsFilterType = "dir"
)

// for schema
var portainerPerDevConfigsFilterTypeEnum []any

func init() {
	var res []PortainerPerDevConfigsFilterType
	if err := json.Unmarshal([]byte(`["file","dir"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		portainerPerDevConfigsFilterTypeEnum = append(portainerPerDevConfigsFilterTypeEnum, v)
	}
}

func (m PortainerPerDevConfigsFilterType) validatePortainerPerDevConfigsFilterTypeEnum(path, location string, value PortainerPerDevConfigsFilterType) error {
	if err := validate.EnumCase(path, location, value, portainerPerDevConfigsFilterTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this portainer per dev configs filter type
func (m PortainerPerDevConfigsFilterType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePortainerPerDevConfigsFilterTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this portainer per dev configs filter type based on context it is used
func (m PortainerPerDevConfigsFilterType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
