// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PortainerResourceControlType portainer resource control type
//
// swagger:model portainer.ResourceControlType
type PortainerResourceControlType int64

// for schema
var portainerResourceControlTypeEnum []any

func init() {
	var res []PortainerResourceControlType
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5,6,7,8,9]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		portainerResourceControlTypeEnum = append(portainerResourceControlTypeEnum, v)
	}
}

func (m PortainerResourceControlType) validatePortainerResourceControlTypeEnum(path, location string, value PortainerResourceControlType) error {
	if err := validate.EnumCase(path, location, value, portainerResourceControlTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this portainer resource control type
func (m PortainerResourceControlType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePortainerResourceControlTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this portainer resource control type based on context it is used
func (m PortainerResourceControlType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
