// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PortainerRegistryType portainer registry type
//
// swagger:model portainer.RegistryType
type PortainerRegistryType int64

// for schema
var portainerRegistryTypeEnum []any

func init() {
	var res []PortainerRegistryType
	if err := json.Unmarshal([]byte(`[0,1,2,3,4,5,6,7,8]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		portainerRegistryTypeEnum = append(portainerRegistryTypeEnum, v)
	}
}

func (m PortainerRegistryType) validatePortainerRegistryTypeEnum(path, location string, value PortainerRegistryType) error {
	if err := validate.EnumCase(path, location, value, portainerRegistryTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this portainer registry type
func (m PortainerRegistryType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePortainerRegistryTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this portainer registry type based on context it is used
func (m PortainerRegistryType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
