// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TypesEnvironmentMetadata types environment metadata
//
// swagger:model types.EnvironmentMetadata
type TypesEnvironmentMetadata struct {

	// custom template content
	CustomTemplateContent string `json:"customTemplateContent,omitempty"`

	// custom template ID
	CustomTemplateID int64 `json:"customTemplateID,omitempty"`

	// group Id
	GroupID int64 `json:"groupId,omitempty"`

	// stack name
	StackName string `json:"stackName,omitempty"`

	// tag ids
	TagIds []int64 `json:"tagIds"`
}

// Validate validates this types environment metadata
func (m *TypesEnvironmentMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this types environment metadata based on context it is used
func (m *TypesEnvironmentMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TypesEnvironmentMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TypesEnvironmentMetadata) UnmarshalBinary(b []byte) error {
	var res TypesEnvironmentMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
