// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1LoadBalancerIPMode v1 load balancer IP mode
//
// swagger:model v1.LoadBalancerIPMode
type V1LoadBalancerIPMode string

func NewV1LoadBalancerIPMode(value V1LoadBalancerIPMode) *V1LoadBalancerIPMode {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1LoadBalancerIPMode.
func (m V1LoadBalancerIPMode) Pointer() *V1LoadBalancerIPMode {
	return &m
}

const (

	// V1LoadBalancerIPModeVIP captures enum value "VIP"
	V1LoadBalancerIPModeVIP V1LoadBalancerIPMode = "VIP"

	// V1LoadBalancerIPModeProxy captures enum value "Proxy"
	V1LoadBalancerIPModeProxy V1LoadBalancerIPMode = "Proxy"
)

// for schema
var v1LoadBalancerIpModeEnum []any

func init() {
	var res []V1LoadBalancerIPMode
	if err := json.Unmarshal([]byte(`["VIP","Proxy"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1LoadBalancerIpModeEnum = append(v1LoadBalancerIpModeEnum, v)
	}
}

func (m V1LoadBalancerIPMode) validateV1LoadBalancerIPModeEnum(path, location string, value V1LoadBalancerIPMode) error {
	if err := validate.EnumCase(path, location, value, v1LoadBalancerIpModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 load balancer IP mode
func (m V1LoadBalancerIPMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1LoadBalancerIPModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 load balancer IP mode based on context it is used
func (m V1LoadBalancerIPMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
