// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1NamespacePhase v1 namespace phase
//
// swagger:model v1.NamespacePhase
type V1NamespacePhase string

func NewV1NamespacePhase(value V1NamespacePhase) *V1NamespacePhase {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1NamespacePhase.
func (m V1NamespacePhase) Pointer() *V1NamespacePhase {
	return &m
}

const (

	// V1NamespacePhaseActive captures enum value "Active"
	V1NamespacePhaseActive V1NamespacePhase = "Active"

	// V1NamespacePhaseTerminating captures enum value "Terminating"
	V1NamespacePhaseTerminating V1NamespacePhase = "Terminating"
)

// for schema
var v1NamespacePhaseEnum []any

func init() {
	var res []V1NamespacePhase
	if err := json.Unmarshal([]byte(`["Active","Terminating"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1NamespacePhaseEnum = append(v1NamespacePhaseEnum, v)
	}
}

func (m V1NamespacePhase) validateV1NamespacePhaseEnum(path, location string, value V1NamespacePhase) error {
	if err := validate.EnumCase(path, location, value, v1NamespacePhaseEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 namespace phase
func (m V1NamespacePhase) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1NamespacePhaseEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 namespace phase based on context it is used
func (m V1NamespacePhase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
