// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1ServiceExternalTrafficPolicy v1 service external traffic policy
//
// swagger:model v1.ServiceExternalTrafficPolicy
type V1ServiceExternalTrafficPolicy string

func NewV1ServiceExternalTrafficPolicy(value V1ServiceExternalTrafficPolicy) *V1ServiceExternalTrafficPolicy {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1ServiceExternalTrafficPolicy.
func (m V1ServiceExternalTrafficPolicy) Pointer() *V1ServiceExternalTrafficPolicy {
	return &m
}

const (

	// V1ServiceExternalTrafficPolicyCluster captures enum value "Cluster"
	V1ServiceExternalTrafficPolicyCluster V1ServiceExternalTrafficPolicy = "Cluster"

	// V1ServiceExternalTrafficPolicyLocal captures enum value "Local"
	V1ServiceExternalTrafficPolicyLocal V1ServiceExternalTrafficPolicy = "Local"
)

// for schema
var v1ServiceExternalTrafficPolicyEnum []any

func init() {
	var res []V1ServiceExternalTrafficPolicy
	if err := json.Unmarshal([]byte(`["Cluster","Local"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1ServiceExternalTrafficPolicyEnum = append(v1ServiceExternalTrafficPolicyEnum, v)
	}
}

func (m V1ServiceExternalTrafficPolicy) validateV1ServiceExternalTrafficPolicyEnum(path, location string, value V1ServiceExternalTrafficPolicy) error {
	if err := validate.EnumCase(path, location, value, v1ServiceExternalTrafficPolicyEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 service external traffic policy
func (m V1ServiceExternalTrafficPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1ServiceExternalTrafficPolicyEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 service external traffic policy based on context it is used
func (m V1ServiceExternalTrafficPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
