// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V2HorizontalPodAutoscalerConditionType v2 horizontal pod autoscaler condition type
//
// swagger:model v2.HorizontalPodAutoscalerConditionType
type V2HorizontalPodAutoscalerConditionType string

func NewV2HorizontalPodAutoscalerConditionType(value V2HorizontalPodAutoscalerConditionType) *V2HorizontalPodAutoscalerConditionType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V2HorizontalPodAutoscalerConditionType.
func (m V2HorizontalPodAutoscalerConditionType) Pointer() *V2HorizontalPodAutoscalerConditionType {
	return &m
}

const (

	// V2HorizontalPodAutoscalerConditionTypeScalingActive captures enum value "ScalingActive"
	V2HorizontalPodAutoscalerConditionTypeScalingActive V2HorizontalPodAutoscalerConditionType = "ScalingActive"

	// V2HorizontalPodAutoscalerConditionTypeAbleToScale captures enum value "AbleToScale"
	V2HorizontalPodAutoscalerConditionTypeAbleToScale V2HorizontalPodAutoscalerConditionType = "AbleToScale"

	// V2HorizontalPodAutoscalerConditionTypeScalingLimited captures enum value "ScalingLimited"
	V2HorizontalPodAutoscalerConditionTypeScalingLimited V2HorizontalPodAutoscalerConditionType = "ScalingLimited"
)

// for schema
var v2HorizontalPodAutoscalerConditionTypeEnum []any

func init() {
	var res []V2HorizontalPodAutoscalerConditionType
	if err := json.Unmarshal([]byte(`["ScalingActive","AbleToScale","ScalingLimited"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v2HorizontalPodAutoscalerConditionTypeEnum = append(v2HorizontalPodAutoscalerConditionTypeEnum, v)
	}
}

func (m V2HorizontalPodAutoscalerConditionType) validateV2HorizontalPodAutoscalerConditionTypeEnum(path, location string, value V2HorizontalPodAutoscalerConditionType) error {
	if err := validate.EnumCase(path, location, value, v2HorizontalPodAutoscalerConditionTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v2 horizontal pod autoscaler condition type
func (m V2HorizontalPodAutoscalerConditionType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV2HorizontalPodAutoscalerConditionTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v2 horizontal pod autoscaler condition type based on context it is used
func (m V2HorizontalPodAutoscalerConditionType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
