// Code generated by go-swagger; DO NOT EDIT.

package edge_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// EdgeJobTasksListReader is a Reader for the EdgeJobTasksList structure.
type EdgeJobTasksListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeJobTasksListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeJobTasksListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeJobTasksListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeJobTasksListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEdgeJobTasksListServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /edge_jobs/{id}/tasks] EdgeJobTasksList", response, response.Code())
	}
}

// NewEdgeJobTasksListOK creates a EdgeJobTasksListOK with default headers values
func NewEdgeJobTasksListOK() *EdgeJobTasksListOK {
	return &EdgeJobTasksListOK{}
}

/*
EdgeJobTasksListOK describes a response with status code 200, with default header values.

OK
*/
type EdgeJobTasksListOK struct {
	Payload []*models.EdgejobsTaskContainer
}

// IsSuccess returns true when this edge job tasks list o k response has a 2xx status code
func (o *EdgeJobTasksListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge job tasks list o k response has a 3xx status code
func (o *EdgeJobTasksListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge job tasks list o k response has a 4xx status code
func (o *EdgeJobTasksListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge job tasks list o k response has a 5xx status code
func (o *EdgeJobTasksListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge job tasks list o k response a status code equal to that given
func (o *EdgeJobTasksListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge job tasks list o k response
func (o *EdgeJobTasksListOK) Code() int {
	return 200
}

func (o *EdgeJobTasksListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListOK %s", 200, payload)
}

func (o *EdgeJobTasksListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListOK %s", 200, payload)
}

func (o *EdgeJobTasksListOK) GetPayload() []*models.EdgejobsTaskContainer {
	return o.Payload
}

func (o *EdgeJobTasksListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewEdgeJobTasksListBadRequest creates a EdgeJobTasksListBadRequest with default headers values
func NewEdgeJobTasksListBadRequest() *EdgeJobTasksListBadRequest {
	return &EdgeJobTasksListBadRequest{}
}

/*
EdgeJobTasksListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type EdgeJobTasksListBadRequest struct {
}

// IsSuccess returns true when this edge job tasks list bad request response has a 2xx status code
func (o *EdgeJobTasksListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge job tasks list bad request response has a 3xx status code
func (o *EdgeJobTasksListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge job tasks list bad request response has a 4xx status code
func (o *EdgeJobTasksListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge job tasks list bad request response has a 5xx status code
func (o *EdgeJobTasksListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge job tasks list bad request response a status code equal to that given
func (o *EdgeJobTasksListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge job tasks list bad request response
func (o *EdgeJobTasksListBadRequest) Code() int {
	return 400
}

func (o *EdgeJobTasksListBadRequest) Error() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListBadRequest", 400)
}

func (o *EdgeJobTasksListBadRequest) String() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListBadRequest", 400)
}

func (o *EdgeJobTasksListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeJobTasksListInternalServerError creates a EdgeJobTasksListInternalServerError with default headers values
func NewEdgeJobTasksListInternalServerError() *EdgeJobTasksListInternalServerError {
	return &EdgeJobTasksListInternalServerError{}
}

/*
EdgeJobTasksListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type EdgeJobTasksListInternalServerError struct {
}

// IsSuccess returns true when this edge job tasks list internal server error response has a 2xx status code
func (o *EdgeJobTasksListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge job tasks list internal server error response has a 3xx status code
func (o *EdgeJobTasksListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge job tasks list internal server error response has a 4xx status code
func (o *EdgeJobTasksListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge job tasks list internal server error response has a 5xx status code
func (o *EdgeJobTasksListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge job tasks list internal server error response a status code equal to that given
func (o *EdgeJobTasksListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge job tasks list internal server error response
func (o *EdgeJobTasksListInternalServerError) Code() int {
	return 500
}

func (o *EdgeJobTasksListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListInternalServerError", 500)
}

func (o *EdgeJobTasksListInternalServerError) String() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListInternalServerError", 500)
}

func (o *EdgeJobTasksListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeJobTasksListServiceUnavailable creates a EdgeJobTasksListServiceUnavailable with default headers values
func NewEdgeJobTasksListServiceUnavailable() *EdgeJobTasksListServiceUnavailable {
	return &EdgeJobTasksListServiceUnavailable{}
}

/*
EdgeJobTasksListServiceUnavailable describes a response with status code 503, with default header values.

Edge compute features are disabled
*/
type EdgeJobTasksListServiceUnavailable struct {
}

// IsSuccess returns true when this edge job tasks list service unavailable response has a 2xx status code
func (o *EdgeJobTasksListServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge job tasks list service unavailable response has a 3xx status code
func (o *EdgeJobTasksListServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge job tasks list service unavailable response has a 4xx status code
func (o *EdgeJobTasksListServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge job tasks list service unavailable response has a 5xx status code
func (o *EdgeJobTasksListServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this edge job tasks list service unavailable response a status code equal to that given
func (o *EdgeJobTasksListServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the edge job tasks list service unavailable response
func (o *EdgeJobTasksListServiceUnavailable) Code() int {
	return 503
}

func (o *EdgeJobTasksListServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListServiceUnavailable", 503)
}

func (o *EdgeJobTasksListServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /edge_jobs/{id}/tasks][%d] edgeJobTasksListServiceUnavailable", 503)
}

func (o *EdgeJobTasksListServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
