// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// StackCreateDockerStandaloneStringReader is a Reader for the StackCreateDockerStandaloneString structure.
type StackCreateDockerStandaloneStringReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StackCreateDockerStandaloneStringReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewStackCreateDockerStandaloneStringOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStackCreateDockerStandaloneStringBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewStackCreateDockerStandaloneStringInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /stacks/create/standalone/string] StackCreateDockerStandaloneString", response, response.Code())
	}
}

// NewStackCreateDockerStandaloneStringOK creates a StackCreateDockerStandaloneStringOK with default headers values
func NewStackCreateDockerStandaloneStringOK() *StackCreateDockerStandaloneStringOK {
	return &StackCreateDockerStandaloneStringOK{}
}

/*
StackCreateDockerStandaloneStringOK describes a response with status code 200, with default header values.

OK
*/
type StackCreateDockerStandaloneStringOK struct {
	Payload *models.PortainereeStack
}

// IsSuccess returns true when this stack create docker standalone string o k response has a 2xx status code
func (o *StackCreateDockerStandaloneStringOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stack create docker standalone string o k response has a 3xx status code
func (o *StackCreateDockerStandaloneStringOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack create docker standalone string o k response has a 4xx status code
func (o *StackCreateDockerStandaloneStringOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stack create docker standalone string o k response has a 5xx status code
func (o *StackCreateDockerStandaloneStringOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stack create docker standalone string o k response a status code equal to that given
func (o *StackCreateDockerStandaloneStringOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the stack create docker standalone string o k response
func (o *StackCreateDockerStandaloneStringOK) Code() int {
	return 200
}

func (o *StackCreateDockerStandaloneStringOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringOK %s", 200, payload)
}

func (o *StackCreateDockerStandaloneStringOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringOK %s", 200, payload)
}

func (o *StackCreateDockerStandaloneStringOK) GetPayload() *models.PortainereeStack {
	return o.Payload
}

func (o *StackCreateDockerStandaloneStringOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortainereeStack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewStackCreateDockerStandaloneStringBadRequest creates a StackCreateDockerStandaloneStringBadRequest with default headers values
func NewStackCreateDockerStandaloneStringBadRequest() *StackCreateDockerStandaloneStringBadRequest {
	return &StackCreateDockerStandaloneStringBadRequest{}
}

/*
StackCreateDockerStandaloneStringBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type StackCreateDockerStandaloneStringBadRequest struct {
}

// IsSuccess returns true when this stack create docker standalone string bad request response has a 2xx status code
func (o *StackCreateDockerStandaloneStringBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this stack create docker standalone string bad request response has a 3xx status code
func (o *StackCreateDockerStandaloneStringBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack create docker standalone string bad request response has a 4xx status code
func (o *StackCreateDockerStandaloneStringBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this stack create docker standalone string bad request response has a 5xx status code
func (o *StackCreateDockerStandaloneStringBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this stack create docker standalone string bad request response a status code equal to that given
func (o *StackCreateDockerStandaloneStringBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the stack create docker standalone string bad request response
func (o *StackCreateDockerStandaloneStringBadRequest) Code() int {
	return 400
}

func (o *StackCreateDockerStandaloneStringBadRequest) Error() string {
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringBadRequest", 400)
}

func (o *StackCreateDockerStandaloneStringBadRequest) String() string {
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringBadRequest", 400)
}

func (o *StackCreateDockerStandaloneStringBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStackCreateDockerStandaloneStringInternalServerError creates a StackCreateDockerStandaloneStringInternalServerError with default headers values
func NewStackCreateDockerStandaloneStringInternalServerError() *StackCreateDockerStandaloneStringInternalServerError {
	return &StackCreateDockerStandaloneStringInternalServerError{}
}

/*
StackCreateDockerStandaloneStringInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type StackCreateDockerStandaloneStringInternalServerError struct {
}

// IsSuccess returns true when this stack create docker standalone string internal server error response has a 2xx status code
func (o *StackCreateDockerStandaloneStringInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this stack create docker standalone string internal server error response has a 3xx status code
func (o *StackCreateDockerStandaloneStringInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack create docker standalone string internal server error response has a 4xx status code
func (o *StackCreateDockerStandaloneStringInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this stack create docker standalone string internal server error response has a 5xx status code
func (o *StackCreateDockerStandaloneStringInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this stack create docker standalone string internal server error response a status code equal to that given
func (o *StackCreateDockerStandaloneStringInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the stack create docker standalone string internal server error response
func (o *StackCreateDockerStandaloneStringInternalServerError) Code() int {
	return 500
}

func (o *StackCreateDockerStandaloneStringInternalServerError) Error() string {
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringInternalServerError", 500)
}

func (o *StackCreateDockerStandaloneStringInternalServerError) String() string {
	return fmt.Sprintf("[POST /stacks/create/standalone/string][%d] stackCreateDockerStandaloneStringInternalServerError", 500)
}

func (o *StackCreateDockerStandaloneStringInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
