// Code generated by go-swagger; DO NOT EDIT.

package observability

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateSilenceReader is a Reader for the CreateSilence structure.
type CreateSilenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSilenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSilenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSilenceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateSilenceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateSilenceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSilenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /observability/alerting/silence] CreateSilence", response, response.Code())
	}
}

// NewCreateSilenceOK creates a CreateSilenceOK with default headers values
func NewCreateSilenceOK() *CreateSilenceOK {
	return &CreateSilenceOK{}
}

/*
CreateSilenceOK describes a response with status code 200, with default header values.

Success
*/
type CreateSilenceOK struct {
	Payload any
}

// IsSuccess returns true when this create silence o k response has a 2xx status code
func (o *CreateSilenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create silence o k response has a 3xx status code
func (o *CreateSilenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create silence o k response has a 4xx status code
func (o *CreateSilenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create silence o k response has a 5xx status code
func (o *CreateSilenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create silence o k response a status code equal to that given
func (o *CreateSilenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create silence o k response
func (o *CreateSilenceOK) Code() int {
	return 200
}

func (o *CreateSilenceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceOK %s", 200, payload)
}

func (o *CreateSilenceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceOK %s", 200, payload)
}

func (o *CreateSilenceOK) GetPayload() any {
	return o.Payload
}

func (o *CreateSilenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateSilenceBadRequest creates a CreateSilenceBadRequest with default headers values
func NewCreateSilenceBadRequest() *CreateSilenceBadRequest {
	return &CreateSilenceBadRequest{}
}

/*
CreateSilenceBadRequest describes a response with status code 400, with default header values.

Invalid request payload, such as missing required fields or fields not meeting validation criteria.
*/
type CreateSilenceBadRequest struct {
}

// IsSuccess returns true when this create silence bad request response has a 2xx status code
func (o *CreateSilenceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create silence bad request response has a 3xx status code
func (o *CreateSilenceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create silence bad request response has a 4xx status code
func (o *CreateSilenceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create silence bad request response has a 5xx status code
func (o *CreateSilenceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create silence bad request response a status code equal to that given
func (o *CreateSilenceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create silence bad request response
func (o *CreateSilenceBadRequest) Code() int {
	return 400
}

func (o *CreateSilenceBadRequest) Error() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceBadRequest", 400)
}

func (o *CreateSilenceBadRequest) String() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceBadRequest", 400)
}

func (o *CreateSilenceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSilenceUnauthorized creates a CreateSilenceUnauthorized with default headers values
func NewCreateSilenceUnauthorized() *CreateSilenceUnauthorized {
	return &CreateSilenceUnauthorized{}
}

/*
CreateSilenceUnauthorized describes a response with status code 401, with default header values.

Unauthorized access - the user is not authenticated or does not have the necessary permissions. Ensure that you have provided a valid API key or JWT token, and that you have the required permissions.
*/
type CreateSilenceUnauthorized struct {
}

// IsSuccess returns true when this create silence unauthorized response has a 2xx status code
func (o *CreateSilenceUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create silence unauthorized response has a 3xx status code
func (o *CreateSilenceUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create silence unauthorized response has a 4xx status code
func (o *CreateSilenceUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create silence unauthorized response has a 5xx status code
func (o *CreateSilenceUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create silence unauthorized response a status code equal to that given
func (o *CreateSilenceUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create silence unauthorized response
func (o *CreateSilenceUnauthorized) Code() int {
	return 401
}

func (o *CreateSilenceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceUnauthorized", 401)
}

func (o *CreateSilenceUnauthorized) String() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceUnauthorized", 401)
}

func (o *CreateSilenceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSilenceForbidden creates a CreateSilenceForbidden with default headers values
func NewCreateSilenceForbidden() *CreateSilenceForbidden {
	return &CreateSilenceForbidden{}
}

/*
CreateSilenceForbidden describes a response with status code 403, with default header values.

Permission denied - the user is authenticated but does not have the necessary permissions to access the requested resource or perform the specified operation. Check your user roles and permissions.
*/
type CreateSilenceForbidden struct {
}

// IsSuccess returns true when this create silence forbidden response has a 2xx status code
func (o *CreateSilenceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create silence forbidden response has a 3xx status code
func (o *CreateSilenceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create silence forbidden response has a 4xx status code
func (o *CreateSilenceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create silence forbidden response has a 5xx status code
func (o *CreateSilenceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create silence forbidden response a status code equal to that given
func (o *CreateSilenceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create silence forbidden response
func (o *CreateSilenceForbidden) Code() int {
	return 403
}

func (o *CreateSilenceForbidden) Error() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceForbidden", 403)
}

func (o *CreateSilenceForbidden) String() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceForbidden", 403)
}

func (o *CreateSilenceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSilenceInternalServerError creates a CreateSilenceInternalServerError with default headers values
func NewCreateSilenceInternalServerError() *CreateSilenceInternalServerError {
	return &CreateSilenceInternalServerError{}
}

/*
CreateSilenceInternalServerError describes a response with status code 500, with default header values.

Server error occurred while attempting to create the alert silence.
*/
type CreateSilenceInternalServerError struct {
}

// IsSuccess returns true when this create silence internal server error response has a 2xx status code
func (o *CreateSilenceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create silence internal server error response has a 3xx status code
func (o *CreateSilenceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create silence internal server error response has a 4xx status code
func (o *CreateSilenceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create silence internal server error response has a 5xx status code
func (o *CreateSilenceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create silence internal server error response a status code equal to that given
func (o *CreateSilenceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create silence internal server error response
func (o *CreateSilenceInternalServerError) Code() int {
	return 500
}

func (o *CreateSilenceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceInternalServerError", 500)
}

func (o *CreateSilenceInternalServerError) String() string {
	return fmt.Sprintf("[POST /observability/alerting/silence][%d] createSilenceInternalServerError", 500)
}

func (o *CreateSilenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
