// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EdgeStackLogsCollectReader is a Reader for the EdgeStackLogsCollect structure.
type EdgeStackLogsCollectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeStackLogsCollectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewEdgeStackLogsCollectNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeStackLogsCollectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeStackLogsCollectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeStackLogsCollectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEdgeStackLogsCollectServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /edge_stacks/{id}/logs/{endpoint_id}] EdgeStackLogsCollect", response, response.Code())
	}
}

// NewEdgeStackLogsCollectNoContent creates a EdgeStackLogsCollectNoContent with default headers values
func NewEdgeStackLogsCollectNoContent() *EdgeStackLogsCollectNoContent {
	return &EdgeStackLogsCollectNoContent{}
}

/*
EdgeStackLogsCollectNoContent describes a response with status code 204, with default header values.

No Content
*/
type EdgeStackLogsCollectNoContent struct {
}

// IsSuccess returns true when this edge stack logs collect no content response has a 2xx status code
func (o *EdgeStackLogsCollectNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge stack logs collect no content response has a 3xx status code
func (o *EdgeStackLogsCollectNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs collect no content response has a 4xx status code
func (o *EdgeStackLogsCollectNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs collect no content response has a 5xx status code
func (o *EdgeStackLogsCollectNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs collect no content response a status code equal to that given
func (o *EdgeStackLogsCollectNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the edge stack logs collect no content response
func (o *EdgeStackLogsCollectNoContent) Code() int {
	return 204
}

func (o *EdgeStackLogsCollectNoContent) Error() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectNoContent", 204)
}

func (o *EdgeStackLogsCollectNoContent) String() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectNoContent", 204)
}

func (o *EdgeStackLogsCollectNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsCollectBadRequest creates a EdgeStackLogsCollectBadRequest with default headers values
func NewEdgeStackLogsCollectBadRequest() *EdgeStackLogsCollectBadRequest {
	return &EdgeStackLogsCollectBadRequest{}
}

/*
EdgeStackLogsCollectBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type EdgeStackLogsCollectBadRequest struct {
}

// IsSuccess returns true when this edge stack logs collect bad request response has a 2xx status code
func (o *EdgeStackLogsCollectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs collect bad request response has a 3xx status code
func (o *EdgeStackLogsCollectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs collect bad request response has a 4xx status code
func (o *EdgeStackLogsCollectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge stack logs collect bad request response has a 5xx status code
func (o *EdgeStackLogsCollectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs collect bad request response a status code equal to that given
func (o *EdgeStackLogsCollectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge stack logs collect bad request response
func (o *EdgeStackLogsCollectBadRequest) Code() int {
	return 400
}

func (o *EdgeStackLogsCollectBadRequest) Error() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectBadRequest", 400)
}

func (o *EdgeStackLogsCollectBadRequest) String() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectBadRequest", 400)
}

func (o *EdgeStackLogsCollectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsCollectNotFound creates a EdgeStackLogsCollectNotFound with default headers values
func NewEdgeStackLogsCollectNotFound() *EdgeStackLogsCollectNotFound {
	return &EdgeStackLogsCollectNotFound{}
}

/*
EdgeStackLogsCollectNotFound describes a response with status code 404, with default header values.

Not Found
*/
type EdgeStackLogsCollectNotFound struct {
}

// IsSuccess returns true when this edge stack logs collect not found response has a 2xx status code
func (o *EdgeStackLogsCollectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs collect not found response has a 3xx status code
func (o *EdgeStackLogsCollectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs collect not found response has a 4xx status code
func (o *EdgeStackLogsCollectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge stack logs collect not found response has a 5xx status code
func (o *EdgeStackLogsCollectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs collect not found response a status code equal to that given
func (o *EdgeStackLogsCollectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge stack logs collect not found response
func (o *EdgeStackLogsCollectNotFound) Code() int {
	return 404
}

func (o *EdgeStackLogsCollectNotFound) Error() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectNotFound", 404)
}

func (o *EdgeStackLogsCollectNotFound) String() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectNotFound", 404)
}

func (o *EdgeStackLogsCollectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsCollectInternalServerError creates a EdgeStackLogsCollectInternalServerError with default headers values
func NewEdgeStackLogsCollectInternalServerError() *EdgeStackLogsCollectInternalServerError {
	return &EdgeStackLogsCollectInternalServerError{}
}

/*
EdgeStackLogsCollectInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type EdgeStackLogsCollectInternalServerError struct {
}

// IsSuccess returns true when this edge stack logs collect internal server error response has a 2xx status code
func (o *EdgeStackLogsCollectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs collect internal server error response has a 3xx status code
func (o *EdgeStackLogsCollectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs collect internal server error response has a 4xx status code
func (o *EdgeStackLogsCollectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs collect internal server error response has a 5xx status code
func (o *EdgeStackLogsCollectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge stack logs collect internal server error response a status code equal to that given
func (o *EdgeStackLogsCollectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge stack logs collect internal server error response
func (o *EdgeStackLogsCollectInternalServerError) Code() int {
	return 500
}

func (o *EdgeStackLogsCollectInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectInternalServerError", 500)
}

func (o *EdgeStackLogsCollectInternalServerError) String() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectInternalServerError", 500)
}

func (o *EdgeStackLogsCollectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsCollectServiceUnavailable creates a EdgeStackLogsCollectServiceUnavailable with default headers values
func NewEdgeStackLogsCollectServiceUnavailable() *EdgeStackLogsCollectServiceUnavailable {
	return &EdgeStackLogsCollectServiceUnavailable{}
}

/*
EdgeStackLogsCollectServiceUnavailable describes a response with status code 503, with default header values.

Edge compute features are disabled
*/
type EdgeStackLogsCollectServiceUnavailable struct {
}

// IsSuccess returns true when this edge stack logs collect service unavailable response has a 2xx status code
func (o *EdgeStackLogsCollectServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs collect service unavailable response has a 3xx status code
func (o *EdgeStackLogsCollectServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs collect service unavailable response has a 4xx status code
func (o *EdgeStackLogsCollectServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs collect service unavailable response has a 5xx status code
func (o *EdgeStackLogsCollectServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this edge stack logs collect service unavailable response a status code equal to that given
func (o *EdgeStackLogsCollectServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the edge stack logs collect service unavailable response
func (o *EdgeStackLogsCollectServiceUnavailable) Code() int {
	return 503
}

func (o *EdgeStackLogsCollectServiceUnavailable) Error() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectServiceUnavailable", 503)
}

func (o *EdgeStackLogsCollectServiceUnavailable) String() string {
	return fmt.Sprintf("[PUT /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsCollectServiceUnavailable", 503)
}

func (o *EdgeStackLogsCollectServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
