// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEdgeStackListParams creates a new EdgeStackListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEdgeStackListParams() *EdgeStackListParams {
	return &EdgeStackListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEdgeStackListParamsWithTimeout creates a new EdgeStackListParams object
// with the ability to set a timeout on a request.
func NewEdgeStackListParamsWithTimeout(timeout time.Duration) *EdgeStackListParams {
	return &EdgeStackListParams{
		timeout: timeout,
	}
}

// NewEdgeStackListParamsWithContext creates a new EdgeStackListParams object
// with the ability to set a context for a request.
func NewEdgeStackListParamsWithContext(ctx context.Context) *EdgeStackListParams {
	return &EdgeStackListParams{
		Context: ctx,
	}
}

// NewEdgeStackListParamsWithHTTPClient creates a new EdgeStackListParams object
// with the ability to set a custom HTTPClient for a request.
func NewEdgeStackListParamsWithHTTPClient(client *http.Client) *EdgeStackListParams {
	return &EdgeStackListParams{
		HTTPClient: client,
	}
}

/*
EdgeStackListParams contains all the parameters to send to the API endpoint

	for the edge stack list operation.

	Typically these are written to a http.Request.
*/
type EdgeStackListParams struct {

	/* SummarizeStatuses.

	   when true summarize the edge stack statuses in the StatusSummary field and void the Status field.
	*/
	SummarizeStatuses *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edge stack list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeStackListParams) WithDefaults() *EdgeStackListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edge stack list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeStackListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edge stack list params
func (o *EdgeStackListParams) WithTimeout(timeout time.Duration) *EdgeStackListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edge stack list params
func (o *EdgeStackListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edge stack list params
func (o *EdgeStackListParams) WithContext(ctx context.Context) *EdgeStackListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edge stack list params
func (o *EdgeStackListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edge stack list params
func (o *EdgeStackListParams) WithHTTPClient(client *http.Client) *EdgeStackListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edge stack list params
func (o *EdgeStackListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSummarizeStatuses adds the summarizeStatuses to the edge stack list params
func (o *EdgeStackListParams) WithSummarizeStatuses(summarizeStatuses *bool) *EdgeStackListParams {
	o.SetSummarizeStatuses(summarizeStatuses)
	return o
}

// SetSummarizeStatuses adds the summarizeStatuses to the edge stack list params
func (o *EdgeStackListParams) SetSummarizeStatuses(summarizeStatuses *bool) {
	o.SummarizeStatuses = summarizeStatuses
}

// WriteToRequest writes these params to a swagger request
func (o *EdgeStackListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SummarizeStatuses != nil {

		// query param summarizeStatuses
		var qrSummarizeStatuses bool

		if o.SummarizeStatuses != nil {
			qrSummarizeStatuses = *o.SummarizeStatuses
		}
		qSummarizeStatuses := swag.FormatBool(qrSummarizeStatuses)
		if qSummarizeStatuses != "" {

			if err := r.SetQueryParam("summarizeStatuses", qSummarizeStatuses); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
