// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// NewEdgeStackStatusUpdateParams creates a new EdgeStackStatusUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEdgeStackStatusUpdateParams() *EdgeStackStatusUpdateParams {
	return &EdgeStackStatusUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEdgeStackStatusUpdateParamsWithTimeout creates a new EdgeStackStatusUpdateParams object
// with the ability to set a timeout on a request.
func NewEdgeStackStatusUpdateParamsWithTimeout(timeout time.Duration) *EdgeStackStatusUpdateParams {
	return &EdgeStackStatusUpdateParams{
		timeout: timeout,
	}
}

// NewEdgeStackStatusUpdateParamsWithContext creates a new EdgeStackStatusUpdateParams object
// with the ability to set a context for a request.
func NewEdgeStackStatusUpdateParamsWithContext(ctx context.Context) *EdgeStackStatusUpdateParams {
	return &EdgeStackStatusUpdateParams{
		Context: ctx,
	}
}

// NewEdgeStackStatusUpdateParamsWithHTTPClient creates a new EdgeStackStatusUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewEdgeStackStatusUpdateParamsWithHTTPClient(client *http.Client) *EdgeStackStatusUpdateParams {
	return &EdgeStackStatusUpdateParams{
		HTTPClient: client,
	}
}

/*
EdgeStackStatusUpdateParams contains all the parameters to send to the API endpoint

	for the edge stack status update operation.

	Typically these are written to a http.Request.
*/
type EdgeStackStatusUpdateParams struct {

	/* Body.

	   EdgeStack status payload
	*/
	Body *models.GithubComPortainerPortainerEeAPIHTTPHandlerEdgestacksUpdateStatusPayload

	/* ID.

	   EdgeStack Id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edge stack status update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeStackStatusUpdateParams) WithDefaults() *EdgeStackStatusUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edge stack status update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeStackStatusUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) WithTimeout(timeout time.Duration) *EdgeStackStatusUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) WithContext(ctx context.Context) *EdgeStackStatusUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) WithHTTPClient(client *http.Client) *EdgeStackStatusUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) WithBody(body *models.GithubComPortainerPortainerEeAPIHTTPHandlerEdgestacksUpdateStatusPayload) *EdgeStackStatusUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) SetBody(body *models.GithubComPortainerPortainerEeAPIHTTPHandlerEdgestacksUpdateStatusPayload) {
	o.Body = body
}

// WithID adds the id to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) WithID(id int64) *EdgeStackStatusUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the edge stack status update params
func (o *EdgeStackStatusUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EdgeStackStatusUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
