// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EdgeStackLogsDownloadReader is a Reader for the EdgeStackLogsDownload structure.
type EdgeStackLogsDownloadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeStackLogsDownloadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeStackLogsDownloadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeStackLogsDownloadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeStackLogsDownloadNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeStackLogsDownloadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEdgeStackLogsDownloadServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /edge_stacks/{id}/logs/{endpoint_id}/file] EdgeStackLogsDownload", response, response.Code())
	}
}

// NewEdgeStackLogsDownloadOK creates a EdgeStackLogsDownloadOK with default headers values
func NewEdgeStackLogsDownloadOK() *EdgeStackLogsDownloadOK {
	return &EdgeStackLogsDownloadOK{}
}

/*
EdgeStackLogsDownloadOK describes a response with status code 200, with default header values.

OK
*/
type EdgeStackLogsDownloadOK struct {
}

// IsSuccess returns true when this edge stack logs download o k response has a 2xx status code
func (o *EdgeStackLogsDownloadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge stack logs download o k response has a 3xx status code
func (o *EdgeStackLogsDownloadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs download o k response has a 4xx status code
func (o *EdgeStackLogsDownloadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs download o k response has a 5xx status code
func (o *EdgeStackLogsDownloadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs download o k response a status code equal to that given
func (o *EdgeStackLogsDownloadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge stack logs download o k response
func (o *EdgeStackLogsDownloadOK) Code() int {
	return 200
}

func (o *EdgeStackLogsDownloadOK) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadOK", 200)
}

func (o *EdgeStackLogsDownloadOK) String() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadOK", 200)
}

func (o *EdgeStackLogsDownloadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDownloadBadRequest creates a EdgeStackLogsDownloadBadRequest with default headers values
func NewEdgeStackLogsDownloadBadRequest() *EdgeStackLogsDownloadBadRequest {
	return &EdgeStackLogsDownloadBadRequest{}
}

/*
EdgeStackLogsDownloadBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type EdgeStackLogsDownloadBadRequest struct {
}

// IsSuccess returns true when this edge stack logs download bad request response has a 2xx status code
func (o *EdgeStackLogsDownloadBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs download bad request response has a 3xx status code
func (o *EdgeStackLogsDownloadBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs download bad request response has a 4xx status code
func (o *EdgeStackLogsDownloadBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge stack logs download bad request response has a 5xx status code
func (o *EdgeStackLogsDownloadBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs download bad request response a status code equal to that given
func (o *EdgeStackLogsDownloadBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge stack logs download bad request response
func (o *EdgeStackLogsDownloadBadRequest) Code() int {
	return 400
}

func (o *EdgeStackLogsDownloadBadRequest) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadBadRequest", 400)
}

func (o *EdgeStackLogsDownloadBadRequest) String() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadBadRequest", 400)
}

func (o *EdgeStackLogsDownloadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDownloadNotFound creates a EdgeStackLogsDownloadNotFound with default headers values
func NewEdgeStackLogsDownloadNotFound() *EdgeStackLogsDownloadNotFound {
	return &EdgeStackLogsDownloadNotFound{}
}

/*
EdgeStackLogsDownloadNotFound describes a response with status code 404, with default header values.

Not Found
*/
type EdgeStackLogsDownloadNotFound struct {
}

// IsSuccess returns true when this edge stack logs download not found response has a 2xx status code
func (o *EdgeStackLogsDownloadNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs download not found response has a 3xx status code
func (o *EdgeStackLogsDownloadNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs download not found response has a 4xx status code
func (o *EdgeStackLogsDownloadNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge stack logs download not found response has a 5xx status code
func (o *EdgeStackLogsDownloadNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs download not found response a status code equal to that given
func (o *EdgeStackLogsDownloadNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge stack logs download not found response
func (o *EdgeStackLogsDownloadNotFound) Code() int {
	return 404
}

func (o *EdgeStackLogsDownloadNotFound) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadNotFound", 404)
}

func (o *EdgeStackLogsDownloadNotFound) String() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadNotFound", 404)
}

func (o *EdgeStackLogsDownloadNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDownloadInternalServerError creates a EdgeStackLogsDownloadInternalServerError with default headers values
func NewEdgeStackLogsDownloadInternalServerError() *EdgeStackLogsDownloadInternalServerError {
	return &EdgeStackLogsDownloadInternalServerError{}
}

/*
EdgeStackLogsDownloadInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type EdgeStackLogsDownloadInternalServerError struct {
}

// IsSuccess returns true when this edge stack logs download internal server error response has a 2xx status code
func (o *EdgeStackLogsDownloadInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs download internal server error response has a 3xx status code
func (o *EdgeStackLogsDownloadInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs download internal server error response has a 4xx status code
func (o *EdgeStackLogsDownloadInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs download internal server error response has a 5xx status code
func (o *EdgeStackLogsDownloadInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge stack logs download internal server error response a status code equal to that given
func (o *EdgeStackLogsDownloadInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge stack logs download internal server error response
func (o *EdgeStackLogsDownloadInternalServerError) Code() int {
	return 500
}

func (o *EdgeStackLogsDownloadInternalServerError) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadInternalServerError", 500)
}

func (o *EdgeStackLogsDownloadInternalServerError) String() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadInternalServerError", 500)
}

func (o *EdgeStackLogsDownloadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDownloadServiceUnavailable creates a EdgeStackLogsDownloadServiceUnavailable with default headers values
func NewEdgeStackLogsDownloadServiceUnavailable() *EdgeStackLogsDownloadServiceUnavailable {
	return &EdgeStackLogsDownloadServiceUnavailable{}
}

/*
EdgeStackLogsDownloadServiceUnavailable describes a response with status code 503, with default header values.

Edge compute features are disabled
*/
type EdgeStackLogsDownloadServiceUnavailable struct {
}

// IsSuccess returns true when this edge stack logs download service unavailable response has a 2xx status code
func (o *EdgeStackLogsDownloadServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs download service unavailable response has a 3xx status code
func (o *EdgeStackLogsDownloadServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs download service unavailable response has a 4xx status code
func (o *EdgeStackLogsDownloadServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs download service unavailable response has a 5xx status code
func (o *EdgeStackLogsDownloadServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this edge stack logs download service unavailable response a status code equal to that given
func (o *EdgeStackLogsDownloadServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the edge stack logs download service unavailable response
func (o *EdgeStackLogsDownloadServiceUnavailable) Code() int {
	return 503
}

func (o *EdgeStackLogsDownloadServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadServiceUnavailable", 503)
}

func (o *EdgeStackLogsDownloadServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}/logs/{endpoint_id}/file][%d] edgeStackLogsDownloadServiceUnavailable", 503)
}

func (o *EdgeStackLogsDownloadServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
