// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EdgeStackLogsDeleteReader is a Reader for the EdgeStackLogsDelete structure.
type EdgeStackLogsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeStackLogsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewEdgeStackLogsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeStackLogsDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEdgeStackLogsDeleteServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /edge_stacks/{id}/logs/{endpoint_id}] EdgeStackLogsDelete", response, response.Code())
	}
}

// NewEdgeStackLogsDeleteNoContent creates a EdgeStackLogsDeleteNoContent with default headers values
func NewEdgeStackLogsDeleteNoContent() *EdgeStackLogsDeleteNoContent {
	return &EdgeStackLogsDeleteNoContent{}
}

/*
EdgeStackLogsDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type EdgeStackLogsDeleteNoContent struct {
}

// IsSuccess returns true when this edge stack logs delete no content response has a 2xx status code
func (o *EdgeStackLogsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge stack logs delete no content response has a 3xx status code
func (o *EdgeStackLogsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs delete no content response has a 4xx status code
func (o *EdgeStackLogsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs delete no content response has a 5xx status code
func (o *EdgeStackLogsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs delete no content response a status code equal to that given
func (o *EdgeStackLogsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the edge stack logs delete no content response
func (o *EdgeStackLogsDeleteNoContent) Code() int {
	return 204
}

func (o *EdgeStackLogsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteNoContent", 204)
}

func (o *EdgeStackLogsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteNoContent", 204)
}

func (o *EdgeStackLogsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDeleteBadRequest creates a EdgeStackLogsDeleteBadRequest with default headers values
func NewEdgeStackLogsDeleteBadRequest() *EdgeStackLogsDeleteBadRequest {
	return &EdgeStackLogsDeleteBadRequest{}
}

/*
EdgeStackLogsDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type EdgeStackLogsDeleteBadRequest struct {
}

// IsSuccess returns true when this edge stack logs delete bad request response has a 2xx status code
func (o *EdgeStackLogsDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs delete bad request response has a 3xx status code
func (o *EdgeStackLogsDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs delete bad request response has a 4xx status code
func (o *EdgeStackLogsDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge stack logs delete bad request response has a 5xx status code
func (o *EdgeStackLogsDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge stack logs delete bad request response a status code equal to that given
func (o *EdgeStackLogsDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge stack logs delete bad request response
func (o *EdgeStackLogsDeleteBadRequest) Code() int {
	return 400
}

func (o *EdgeStackLogsDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteBadRequest", 400)
}

func (o *EdgeStackLogsDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteBadRequest", 400)
}

func (o *EdgeStackLogsDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackLogsDeleteServiceUnavailable creates a EdgeStackLogsDeleteServiceUnavailable with default headers values
func NewEdgeStackLogsDeleteServiceUnavailable() *EdgeStackLogsDeleteServiceUnavailable {
	return &EdgeStackLogsDeleteServiceUnavailable{}
}

/*
EdgeStackLogsDeleteServiceUnavailable describes a response with status code 503, with default header values.

Edge compute features are disabled
*/
type EdgeStackLogsDeleteServiceUnavailable struct {
}

// IsSuccess returns true when this edge stack logs delete service unavailable response has a 2xx status code
func (o *EdgeStackLogsDeleteServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge stack logs delete service unavailable response has a 3xx status code
func (o *EdgeStackLogsDeleteServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge stack logs delete service unavailable response has a 4xx status code
func (o *EdgeStackLogsDeleteServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge stack logs delete service unavailable response has a 5xx status code
func (o *EdgeStackLogsDeleteServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this edge stack logs delete service unavailable response a status code equal to that given
func (o *EdgeStackLogsDeleteServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the edge stack logs delete service unavailable response
func (o *EdgeStackLogsDeleteServiceUnavailable) Code() int {
	return 503
}

func (o *EdgeStackLogsDeleteServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteServiceUnavailable", 503)
}

func (o *EdgeStackLogsDeleteServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /edge_stacks/{id}/logs/{endpoint_id}][%d] edgeStackLogsDeleteServiceUnavailable", 503)
}

func (o *EdgeStackLogsDeleteServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
