// Code generated by go-swagger; DO NOT EDIT.

package custom_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// CustomTemplateInspectReader is a Reader for the CustomTemplateInspect structure.
type CustomTemplateInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomTemplateInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCustomTemplateInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCustomTemplateInspectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCustomTemplateInspectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCustomTemplateInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /custom_templates/{id}] CustomTemplateInspect", response, response.Code())
	}
}

// NewCustomTemplateInspectOK creates a CustomTemplateInspectOK with default headers values
func NewCustomTemplateInspectOK() *CustomTemplateInspectOK {
	return &CustomTemplateInspectOK{}
}

/*
CustomTemplateInspectOK describes a response with status code 200, with default header values.

Success
*/
type CustomTemplateInspectOK struct {
	Payload *models.PortainereeCustomTemplate
}

// IsSuccess returns true when this custom template inspect o k response has a 2xx status code
func (o *CustomTemplateInspectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this custom template inspect o k response has a 3xx status code
func (o *CustomTemplateInspectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template inspect o k response has a 4xx status code
func (o *CustomTemplateInspectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template inspect o k response has a 5xx status code
func (o *CustomTemplateInspectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template inspect o k response a status code equal to that given
func (o *CustomTemplateInspectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the custom template inspect o k response
func (o *CustomTemplateInspectOK) Code() int {
	return 200
}

func (o *CustomTemplateInspectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectOK %s", 200, payload)
}

func (o *CustomTemplateInspectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectOK %s", 200, payload)
}

func (o *CustomTemplateInspectOK) GetPayload() *models.PortainereeCustomTemplate {
	return o.Payload
}

func (o *CustomTemplateInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortainereeCustomTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCustomTemplateInspectBadRequest creates a CustomTemplateInspectBadRequest with default headers values
func NewCustomTemplateInspectBadRequest() *CustomTemplateInspectBadRequest {
	return &CustomTemplateInspectBadRequest{}
}

/*
CustomTemplateInspectBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CustomTemplateInspectBadRequest struct {
}

// IsSuccess returns true when this custom template inspect bad request response has a 2xx status code
func (o *CustomTemplateInspectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template inspect bad request response has a 3xx status code
func (o *CustomTemplateInspectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template inspect bad request response has a 4xx status code
func (o *CustomTemplateInspectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this custom template inspect bad request response has a 5xx status code
func (o *CustomTemplateInspectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template inspect bad request response a status code equal to that given
func (o *CustomTemplateInspectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the custom template inspect bad request response
func (o *CustomTemplateInspectBadRequest) Code() int {
	return 400
}

func (o *CustomTemplateInspectBadRequest) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectBadRequest", 400)
}

func (o *CustomTemplateInspectBadRequest) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectBadRequest", 400)
}

func (o *CustomTemplateInspectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomTemplateInspectNotFound creates a CustomTemplateInspectNotFound with default headers values
func NewCustomTemplateInspectNotFound() *CustomTemplateInspectNotFound {
	return &CustomTemplateInspectNotFound{}
}

/*
CustomTemplateInspectNotFound describes a response with status code 404, with default header values.

Template not found
*/
type CustomTemplateInspectNotFound struct {
}

// IsSuccess returns true when this custom template inspect not found response has a 2xx status code
func (o *CustomTemplateInspectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template inspect not found response has a 3xx status code
func (o *CustomTemplateInspectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template inspect not found response has a 4xx status code
func (o *CustomTemplateInspectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this custom template inspect not found response has a 5xx status code
func (o *CustomTemplateInspectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template inspect not found response a status code equal to that given
func (o *CustomTemplateInspectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the custom template inspect not found response
func (o *CustomTemplateInspectNotFound) Code() int {
	return 404
}

func (o *CustomTemplateInspectNotFound) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectNotFound", 404)
}

func (o *CustomTemplateInspectNotFound) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectNotFound", 404)
}

func (o *CustomTemplateInspectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomTemplateInspectInternalServerError creates a CustomTemplateInspectInternalServerError with default headers values
func NewCustomTemplateInspectInternalServerError() *CustomTemplateInspectInternalServerError {
	return &CustomTemplateInspectInternalServerError{}
}

/*
CustomTemplateInspectInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CustomTemplateInspectInternalServerError struct {
}

// IsSuccess returns true when this custom template inspect internal server error response has a 2xx status code
func (o *CustomTemplateInspectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template inspect internal server error response has a 3xx status code
func (o *CustomTemplateInspectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template inspect internal server error response has a 4xx status code
func (o *CustomTemplateInspectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template inspect internal server error response has a 5xx status code
func (o *CustomTemplateInspectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this custom template inspect internal server error response a status code equal to that given
func (o *CustomTemplateInspectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the custom template inspect internal server error response
func (o *CustomTemplateInspectInternalServerError) Code() int {
	return 500
}

func (o *CustomTemplateInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectInternalServerError", 500)
}

func (o *CustomTemplateInspectInternalServerError) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}][%d] customTemplateInspectInternalServerError", 500)
}

func (o *CustomTemplateInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
