// Code generated by go-swagger; DO NOT EDIT.

package custom_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// CustomTemplateCreateStringReader is a Reader for the CustomTemplateCreateString structure.
type CustomTemplateCreateStringReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomTemplateCreateStringReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCustomTemplateCreateStringOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCustomTemplateCreateStringBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCustomTemplateCreateStringInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /custom_templates/create/string] CustomTemplateCreateString", response, response.Code())
	}
}

// NewCustomTemplateCreateStringOK creates a CustomTemplateCreateStringOK with default headers values
func NewCustomTemplateCreateStringOK() *CustomTemplateCreateStringOK {
	return &CustomTemplateCreateStringOK{}
}

/*
CustomTemplateCreateStringOK describes a response with status code 200, with default header values.

OK
*/
type CustomTemplateCreateStringOK struct {
	Payload *models.PortainereeCustomTemplate
}

// IsSuccess returns true when this custom template create string o k response has a 2xx status code
func (o *CustomTemplateCreateStringOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this custom template create string o k response has a 3xx status code
func (o *CustomTemplateCreateStringOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template create string o k response has a 4xx status code
func (o *CustomTemplateCreateStringOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template create string o k response has a 5xx status code
func (o *CustomTemplateCreateStringOK) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template create string o k response a status code equal to that given
func (o *CustomTemplateCreateStringOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the custom template create string o k response
func (o *CustomTemplateCreateStringOK) Code() int {
	return 200
}

func (o *CustomTemplateCreateStringOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringOK %s", 200, payload)
}

func (o *CustomTemplateCreateStringOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringOK %s", 200, payload)
}

func (o *CustomTemplateCreateStringOK) GetPayload() *models.PortainereeCustomTemplate {
	return o.Payload
}

func (o *CustomTemplateCreateStringOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortainereeCustomTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCustomTemplateCreateStringBadRequest creates a CustomTemplateCreateStringBadRequest with default headers values
func NewCustomTemplateCreateStringBadRequest() *CustomTemplateCreateStringBadRequest {
	return &CustomTemplateCreateStringBadRequest{}
}

/*
CustomTemplateCreateStringBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CustomTemplateCreateStringBadRequest struct {
}

// IsSuccess returns true when this custom template create string bad request response has a 2xx status code
func (o *CustomTemplateCreateStringBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template create string bad request response has a 3xx status code
func (o *CustomTemplateCreateStringBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template create string bad request response has a 4xx status code
func (o *CustomTemplateCreateStringBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this custom template create string bad request response has a 5xx status code
func (o *CustomTemplateCreateStringBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template create string bad request response a status code equal to that given
func (o *CustomTemplateCreateStringBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the custom template create string bad request response
func (o *CustomTemplateCreateStringBadRequest) Code() int {
	return 400
}

func (o *CustomTemplateCreateStringBadRequest) Error() string {
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringBadRequest", 400)
}

func (o *CustomTemplateCreateStringBadRequest) String() string {
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringBadRequest", 400)
}

func (o *CustomTemplateCreateStringBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomTemplateCreateStringInternalServerError creates a CustomTemplateCreateStringInternalServerError with default headers values
func NewCustomTemplateCreateStringInternalServerError() *CustomTemplateCreateStringInternalServerError {
	return &CustomTemplateCreateStringInternalServerError{}
}

/*
CustomTemplateCreateStringInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CustomTemplateCreateStringInternalServerError struct {
}

// IsSuccess returns true when this custom template create string internal server error response has a 2xx status code
func (o *CustomTemplateCreateStringInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template create string internal server error response has a 3xx status code
func (o *CustomTemplateCreateStringInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template create string internal server error response has a 4xx status code
func (o *CustomTemplateCreateStringInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template create string internal server error response has a 5xx status code
func (o *CustomTemplateCreateStringInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this custom template create string internal server error response a status code equal to that given
func (o *CustomTemplateCreateStringInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the custom template create string internal server error response
func (o *CustomTemplateCreateStringInternalServerError) Code() int {
	return 500
}

func (o *CustomTemplateCreateStringInternalServerError) Error() string {
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringInternalServerError", 500)
}

func (o *CustomTemplateCreateStringInternalServerError) String() string {
	return fmt.Sprintf("[POST /custom_templates/create/string][%d] customTemplateCreateStringInternalServerError", 500)
}

func (o *CustomTemplateCreateStringInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
