// Code generated by go-swagger; DO NOT EDIT.

package custom_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// CustomTemplateFileReader is a Reader for the CustomTemplateFile structure.
type CustomTemplateFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomTemplateFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCustomTemplateFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCustomTemplateFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCustomTemplateFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCustomTemplateFileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /custom_templates/{id}/file] CustomTemplateFile", response, response.Code())
	}
}

// NewCustomTemplateFileOK creates a CustomTemplateFileOK with default headers values
func NewCustomTemplateFileOK() *CustomTemplateFileOK {
	return &CustomTemplateFileOK{}
}

/*
CustomTemplateFileOK describes a response with status code 200, with default header values.

Success
*/
type CustomTemplateFileOK struct {
	Payload *models.CustomtemplatesFileResponse
}

// IsSuccess returns true when this custom template file o k response has a 2xx status code
func (o *CustomTemplateFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this custom template file o k response has a 3xx status code
func (o *CustomTemplateFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template file o k response has a 4xx status code
func (o *CustomTemplateFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template file o k response has a 5xx status code
func (o *CustomTemplateFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template file o k response a status code equal to that given
func (o *CustomTemplateFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the custom template file o k response
func (o *CustomTemplateFileOK) Code() int {
	return 200
}

func (o *CustomTemplateFileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileOK %s", 200, payload)
}

func (o *CustomTemplateFileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileOK %s", 200, payload)
}

func (o *CustomTemplateFileOK) GetPayload() *models.CustomtemplatesFileResponse {
	return o.Payload
}

func (o *CustomTemplateFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomtemplatesFileResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCustomTemplateFileBadRequest creates a CustomTemplateFileBadRequest with default headers values
func NewCustomTemplateFileBadRequest() *CustomTemplateFileBadRequest {
	return &CustomTemplateFileBadRequest{}
}

/*
CustomTemplateFileBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CustomTemplateFileBadRequest struct {
}

// IsSuccess returns true when this custom template file bad request response has a 2xx status code
func (o *CustomTemplateFileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template file bad request response has a 3xx status code
func (o *CustomTemplateFileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template file bad request response has a 4xx status code
func (o *CustomTemplateFileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this custom template file bad request response has a 5xx status code
func (o *CustomTemplateFileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template file bad request response a status code equal to that given
func (o *CustomTemplateFileBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the custom template file bad request response
func (o *CustomTemplateFileBadRequest) Code() int {
	return 400
}

func (o *CustomTemplateFileBadRequest) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileBadRequest", 400)
}

func (o *CustomTemplateFileBadRequest) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileBadRequest", 400)
}

func (o *CustomTemplateFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomTemplateFileNotFound creates a CustomTemplateFileNotFound with default headers values
func NewCustomTemplateFileNotFound() *CustomTemplateFileNotFound {
	return &CustomTemplateFileNotFound{}
}

/*
CustomTemplateFileNotFound describes a response with status code 404, with default header values.

Custom template not found
*/
type CustomTemplateFileNotFound struct {
}

// IsSuccess returns true when this custom template file not found response has a 2xx status code
func (o *CustomTemplateFileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template file not found response has a 3xx status code
func (o *CustomTemplateFileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template file not found response has a 4xx status code
func (o *CustomTemplateFileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this custom template file not found response has a 5xx status code
func (o *CustomTemplateFileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this custom template file not found response a status code equal to that given
func (o *CustomTemplateFileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the custom template file not found response
func (o *CustomTemplateFileNotFound) Code() int {
	return 404
}

func (o *CustomTemplateFileNotFound) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileNotFound", 404)
}

func (o *CustomTemplateFileNotFound) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileNotFound", 404)
}

func (o *CustomTemplateFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomTemplateFileInternalServerError creates a CustomTemplateFileInternalServerError with default headers values
func NewCustomTemplateFileInternalServerError() *CustomTemplateFileInternalServerError {
	return &CustomTemplateFileInternalServerError{}
}

/*
CustomTemplateFileInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CustomTemplateFileInternalServerError struct {
}

// IsSuccess returns true when this custom template file internal server error response has a 2xx status code
func (o *CustomTemplateFileInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this custom template file internal server error response has a 3xx status code
func (o *CustomTemplateFileInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom template file internal server error response has a 4xx status code
func (o *CustomTemplateFileInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom template file internal server error response has a 5xx status code
func (o *CustomTemplateFileInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this custom template file internal server error response a status code equal to that given
func (o *CustomTemplateFileInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the custom template file internal server error response
func (o *CustomTemplateFileInternalServerError) Code() int {
	return 500
}

func (o *CustomTemplateFileInternalServerError) Error() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileInternalServerError", 500)
}

func (o *CustomTemplateFileInternalServerError) String() string {
	return fmt.Sprintf("[GET /custom_templates/{id}/file][%d] customTemplateFileInternalServerError", 500)
}

func (o *CustomTemplateFileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
