// Code generated by go-swagger; DO NOT EDIT.

package gitops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// GitOperationRepoHelmValuesReader is a Reader for the GitOperationRepoHelmValues structure.
type GitOperationRepoHelmValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GitOperationRepoHelmValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGitOperationRepoHelmValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGitOperationRepoHelmValuesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGitOperationRepoHelmValuesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /gitops/repo/helm/values] GitOperationRepoHelmValues", response, response.Code())
	}
}

// NewGitOperationRepoHelmValuesOK creates a GitOperationRepoHelmValuesOK with default headers values
func NewGitOperationRepoHelmValuesOK() *GitOperationRepoHelmValuesOK {
	return &GitOperationRepoHelmValuesOK{}
}

/*
GitOperationRepoHelmValuesOK describes a response with status code 200, with default header values.

Success
*/
type GitOperationRepoHelmValuesOK struct {
	Payload *models.GitopsHelmValuesPreviewResponse
}

// IsSuccess returns true when this git operation repo helm values o k response has a 2xx status code
func (o *GitOperationRepoHelmValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this git operation repo helm values o k response has a 3xx status code
func (o *GitOperationRepoHelmValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this git operation repo helm values o k response has a 4xx status code
func (o *GitOperationRepoHelmValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this git operation repo helm values o k response has a 5xx status code
func (o *GitOperationRepoHelmValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this git operation repo helm values o k response a status code equal to that given
func (o *GitOperationRepoHelmValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the git operation repo helm values o k response
func (o *GitOperationRepoHelmValuesOK) Code() int {
	return 200
}

func (o *GitOperationRepoHelmValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesOK %s", 200, payload)
}

func (o *GitOperationRepoHelmValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesOK %s", 200, payload)
}

func (o *GitOperationRepoHelmValuesOK) GetPayload() *models.GitopsHelmValuesPreviewResponse {
	return o.Payload
}

func (o *GitOperationRepoHelmValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitopsHelmValuesPreviewResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGitOperationRepoHelmValuesBadRequest creates a GitOperationRepoHelmValuesBadRequest with default headers values
func NewGitOperationRepoHelmValuesBadRequest() *GitOperationRepoHelmValuesBadRequest {
	return &GitOperationRepoHelmValuesBadRequest{}
}

/*
GitOperationRepoHelmValuesBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type GitOperationRepoHelmValuesBadRequest struct {
}

// IsSuccess returns true when this git operation repo helm values bad request response has a 2xx status code
func (o *GitOperationRepoHelmValuesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this git operation repo helm values bad request response has a 3xx status code
func (o *GitOperationRepoHelmValuesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this git operation repo helm values bad request response has a 4xx status code
func (o *GitOperationRepoHelmValuesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this git operation repo helm values bad request response has a 5xx status code
func (o *GitOperationRepoHelmValuesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this git operation repo helm values bad request response a status code equal to that given
func (o *GitOperationRepoHelmValuesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the git operation repo helm values bad request response
func (o *GitOperationRepoHelmValuesBadRequest) Code() int {
	return 400
}

func (o *GitOperationRepoHelmValuesBadRequest) Error() string {
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesBadRequest", 400)
}

func (o *GitOperationRepoHelmValuesBadRequest) String() string {
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesBadRequest", 400)
}

func (o *GitOperationRepoHelmValuesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGitOperationRepoHelmValuesInternalServerError creates a GitOperationRepoHelmValuesInternalServerError with default headers values
func NewGitOperationRepoHelmValuesInternalServerError() *GitOperationRepoHelmValuesInternalServerError {
	return &GitOperationRepoHelmValuesInternalServerError{}
}

/*
GitOperationRepoHelmValuesInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type GitOperationRepoHelmValuesInternalServerError struct {
}

// IsSuccess returns true when this git operation repo helm values internal server error response has a 2xx status code
func (o *GitOperationRepoHelmValuesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this git operation repo helm values internal server error response has a 3xx status code
func (o *GitOperationRepoHelmValuesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this git operation repo helm values internal server error response has a 4xx status code
func (o *GitOperationRepoHelmValuesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this git operation repo helm values internal server error response has a 5xx status code
func (o *GitOperationRepoHelmValuesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this git operation repo helm values internal server error response a status code equal to that given
func (o *GitOperationRepoHelmValuesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the git operation repo helm values internal server error response
func (o *GitOperationRepoHelmValuesInternalServerError) Code() int {
	return 500
}

func (o *GitOperationRepoHelmValuesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesInternalServerError", 500)
}

func (o *GitOperationRepoHelmValuesInternalServerError) String() string {
	return fmt.Sprintf("[POST /gitops/repo/helm/values][%d] gitOperationRepoHelmValuesInternalServerError", 500)
}

func (o *GitOperationRepoHelmValuesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
